### PR TITLE
Update cart on init of page load

### PR DESCRIPTION
**Pull request by S3B4S**
It seems the the cart didn't get updated on initial page load, this small function added and executed on init load in should take care of that.

More about the problem can be found here: https://stackoverflow.com/questions/52290225/cart-shows-as-empty-after-change-of-page

### CODE REVIEW

**Comment by tatarincev** [comment]
@S3B4S  Could you sign CLA before I can accept of your PR?

**Comment by S3B4S** [comment]
Done, sorry about that!

**Comment by S3B4S** [comment]
I want to delete the fork from my Github. Could you please either merge or close this depending on what you want to do?

**Comment by tatarincev** [comment]
Done, thanks for you contribution

**Pull request merged**
